<a href="https://colab.research.google.com/github/agborcharles/Codemy-Django-API-Tutorial/blob/master/Introduction_to_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


**Creating Tensors (Strings, Integers and Floats)**

In [6]:
# Strings

string = tf.Variable("this is a string", tf.string) 
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

**Printing Tensors**

In [10]:
print("This is a {} and {}".format(string, number))

This is a <tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'> and <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>


In [11]:
rank1_tensor = tf.Variable(["Test"], tf.string) 
print(rank1_tensor)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'Test'], dtype=object)>


In [12]:
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)
print(rank2_tensor)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'test', b'ok'],
       [b'test', b'yes']], dtype=object)>


In [14]:
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"],["test", "yes"],["test", "yes"]], tf.string)
print(rank2_tensor)

<tf.Variable 'Variable:0' shape=(4, 2) dtype=string, numpy=
array([[b'test', b'ok'],
       [b'test', b'yes'],
       [b'test', b'yes'],
       [b'test', b'yes']], dtype=object)>


**Getting the Rank of a Tensor**

In [17]:
print(tf.rank(rank1_tensor))
print(tf.rank(rank2_tensor))
print(tf.rank(string))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


**Getting the Shape of a Tensor**

In [20]:
rank1_tensor.shape

TensorShape([1])

In [22]:
rank2_tensor.shape

TensorShape([4, 2])

In [23]:
string.shape

TensorShape([])

**Reshaping Tensors**

In [24]:
# Sample Shapes to Reshape
tensor1 = tf.ones([1,2,3]) 

# The result below means that we have one Big List, another 1 list in the Big List and two other list in the 
# inner list, of which each of those list contains 3 elements
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


We can reshape the list to the shape we want as wil be seen in below

In [25]:
 # reshape existing data to shape [2,3,1]
tensor2 = tf.reshape(tensor1, [2,3,1]) 

# One Mega list, Two sub-list, and 3 sub-list containing 1 element each
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [27]:
 # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,3]
tensor3 = tf.reshape(tensor2, [3, -1]) 
print(tensor3)

# One Mega List, Containing 3 sub-list with each list having 2 elements

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [38]:
t = tf.ones([4,4,4,4])
print(t)

tf.Tensor(
[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [

In [39]:
t = tf.reshape(t,[4, -1])
print(t)

tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(4, 64), dtype=float32)


**Slincing Tensors**

In [40]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [41]:
# Now lets select some different rows and columns from our tensor

three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3

tf.Tensor(3, shape=(), dtype=int32)
